<?php
/**
 * Created by PhpStorm.
 * User: Shalitha Suranga
 * Date: 4/20/2017
 * Time: 6:51 AM
 */


require("../includes/config.php");
require("../includes/dompdf-master/dompdf_config.inc.php");
header("Access-Control-Allow-Origin: *");
header('Content-Type: application/json');
if(isset($_GET["token"])){
    if($_GET["token"]==AP_TOKEN){




        /* ------------ grouping ---------------- */


        if(isset($_GET["grouping"])){


            $members=$db->real_escape_string($_GET["members"]);
            $student_id=$db->real_escape_string($_GET["student"]);

            $result=$db->query("SELECT * FROM sm_student WHERE id='$student_id' LIMIT 1");
            $node=$result->fetch_assoc();

            $degree_id=$node["deg_id"];
            $year=$node["cyear"];
            $semester=$node["csemester"];

            $result = $db->query("
            SELECT 
              sm_student.*
            FROM 
                  sm_student
             WHERE
                  
                  sm_student.cyear=$year AND sm_student.csemester=$semester AND sm_student.deg_id=$degree_id
                  
             ORDER BY sm_student.deg_id ASC     
                  
            
            ");
            if ($result->num_rows) {
                $info=array();
                while($node=$result->fetch_assoc()) $info[]=$node;
                shuffle($info);

                $grouped=array();
                $subgroup=array();
                $subc=0;
                $lasti=0;
                for($i=0; $i<sizeof($info); $i++){
                    if($subc<$members){
                        $subgroup[]=$info[$i];
                        $subc++;

                    }
                    if($subc==$members){
                        $grouped[]=$subgroup;
                        $subgroup=array();
                        $subc=0;
                        $lasti=$i+1;
                    }
                }
                if(sizeof($grouped)*$members<sizeof($info)){
                    $subgroup=array();
                    for($i=$lasti; $i<sizeof($info); $i++){
                        $subgroup[]=$info[$i];
                    }
                    $grouped[]=$subgroup;
                }




                /* ------ write to file --------- */
                $con="";
                for($i=0; $i<sizeof($grouped); $i++){
                    $con.="<h3 style='padding: 6px; margin: 0px; background-color: #9acfea'>Group ".($i+1)."</h3>";
                    $con.="<ol>";
                    for($j=0; $j<sizeof($grouped[$i]); $j++){
                        $con.="<li>".$grouped[$i][$j]["id"]."</li>";
                    }
                    $con.="</ol>";
                }
                $con.="<br/><br/><hr/><span>Generated by SmartUni.</span>";
                $dompdf = new DOMPDF();
                $dompdf->load_html($con);
                $dompdf->set_paper("A4", "portrait");
                $dompdf->render();

                $pdfcontent=$dompdf->output();
                $filename="files/Groups-$degree_id-$year-$semester.pdf";

                file_put_contents($filename,$pdfcontent);

                echo(json_encode(array(
                    "groups" => $grouped,
                    "pdf" => $filename
                )));
            } else {
                echo(json_encode(array(
                    "error" => "notfound"
                )));
            }

        }



    }
}